-- =======================================
-- 2) Criar subáreas (cursos)
-- =======================================

-- Linguagens e Códigos
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Letras', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Linguagens e Códigos';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Jornalismo', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Linguagens e Códigos';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Artes Visuais', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Linguagens e Códigos';

-- Matemática
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Matemática', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Matemática';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Engenharia Civil', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Matemática';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Engenharia Mecânica', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Matemática';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Sistemas de Informação', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Matemática';

-- Ciências da Natureza
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Medicina', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências da Natureza';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Enfermagem', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências da Natureza';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Biomedicina', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências da Natureza';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Nutrição', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências da Natureza';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Fisioterapia', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências da Natureza';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Fonoaudiologia', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências da Natureza';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Medicina Veterinária', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências da Natureza';

-- Ciências Humanas
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Direito', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Psicologia', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Gestão de Recursos Humanos', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Educação Física - Bacharelado', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Logística', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Gestão Ambiental', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Terapia Ocupacional', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Odontologia', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';
INSERT INTO AREASUB (AREAS_DESCRICAO, AREA_ID, AREAS_ATIVO, AREAS_DATACADASTRO, AREAS_HORACADASTRO)
SELECT 'Estética e Cosmética', AREA_ID, 1, CURDATE(), CURTIME() FROM AREA WHERE AREA_DESCRICAO='Ciências Humanas';

-- =======================================
-- 3) Criar testes (1 por área principal)
-- =======================================
INSERT INTO TESTE (TES_DATACADASTRO, TES_HORACADASTRO, TES_DESCRICAO, AREA_ID)
SELECT CURDATE(), CURTIME(), CONCAT('Teste de afinidade - ', AREA_DESCRICAO), AREA_ID
FROM AREA;

-- =======================================
-- 4) Inserir questões (2-3 por subárea como exemplo)
-- =======================================

-- Linguagens e Códigos
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Gosto de ler livros, artigos ou textos em geral.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Letras';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Tenho facilidade para escrever textos criativos ou dissertativos.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Jornalismo';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Gosto de analisar filmes, músicas ou obras de arte.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Artes Visuais';

-- Matemática
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Gosto de resolver problemas matemáticos.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Matemática';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Tenho interesse em construir ou projetar estruturas.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Engenharia Civil';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Gosto de estudar máquinas, motores e sistemas mecânicos.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Engenharia Mecânica';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Tenho facilidade com programação e lógica de sistemas.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Sistemas de Informação';

-- Ciências da Natureza
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Tenho interesse em cuidar da saúde das pessoas.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Medicina';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Gosto de estudar biologia e realizar exames laboratoriais.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Biomedicina';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Tenho interesse em prevenir doenças e cuidar da nutrição.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Nutrição';

-- Ciências Humanas
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Tenho interesse em leis e direitos.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Direito';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Tenho interesse em estudar comportamento humano e psicologia.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Psicologia';
INSERT INTO TESTEQUESTAO (TESQ_DATACADASTRO, TESQ_HORACADASTRO, TESQ_DESCRICAO, AREA_ID, AREAS_ID)
SELECT CURDATE(), CURTIME(), 'Tenho interesse em gestão de pessoas e recursos humanos.', AREA_ID, AREAS_ID FROM AREASUB WHERE AREAS_DESCRICAO='Gestão de Recursos Humanos';

-- =======================================
-- 5) Vincular questões aos testes
-- =======================================
INSERT INTO TESTEQUESTAOVINCULO (TES_ID, TESQ_ID)
SELECT t.TES_ID, q.TESQ_ID
FROM TESTE t
JOIN TESTEQUESTAO q ON t.AREA_ID = q.AREA_ID;