

DROP DATABASE IF EXISTS rotafuturo;

CREATE DATABASE rotafuturo;

USE rotafuturo;

CREATE TABLE USUARIO (
    USU_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USU_EMAIL VARCHAR(200) DEFAULT NULL,
    USU_SENHA VARCHAR(250) DEFAULT NULL,
    USU_DATACADASTRO DATE DEFAULT NULL,
    USU_HORACADASTRO TIME DEFAULT NULL,
    USU_EMAILVALIDADO TINYINT(1) DEFAULT '0',
    USU_ATIVO TINYINT(1) DEFAULT '1',
    USU_TROCASENHA TINYINT(1) DEFAULT '0',
    USU_SENHAANTIGA1 VARCHAR(250) DEFAULT NULL,
    USU_SENHAANTIGA2 VARCHAR(250) DEFAULT NULL
);

CREATE TABLE PESSOA (
    PES_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PES_NOME VARCHAR(255),
    PES_APELIDO VARCHAR(255),
    PES_DATACADASTRO DATE,
    PES_HORACADASTRO TIME,
    PES_DATANASCIMENTO DATE,
    PES_TELEFONE1 VARCHAR(20),
    PES_TELEFONE2 VARCHAR(20),
    PES_IMAGEMPERFIL VARCHAR(1000),
    PES_IMAGEMCAPAPERFIL VARCHAR(1000),
    PES_IMAGEMCURRICULO VARCHAR(1000),
    PES_NIVEL INT,
    PES_XP INT,
    PES_ATIVO TINYINT(1) DEFAULT '1',
    USU_ID INT,
    FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID)
);



CREATE TABLE ARQUIVOTIPO (
    ARQT_ID INT PRIMARY KEY AUTO_INCREMENT,
    ARQT_DESCRICAO VARCHAR(255) NOT NULL,
    ARQT_ATIVO TINYINT(1) DEFAULT '1'
);

CREATE TABLE ARQUIVO (
    ARQ_ID INT PRIMARY KEY AUTO_INCREMENT,
    ARQ_DATACADASTRO DATE NOT NULL,
    ARQ_HORACADASTRO TIME NOT NULL,
    ARQ_TAMANHO INT,
    ARQ_DESCRICAO VARCHAR(255),
    ARQ_EXTENSAO VARCHAR(10),
    ARQ_ENDERECO VARCHAR(1000),
    ARQ_ATIVO TINYINT(1) DEFAULT '1',
    ARQT_ID INT,
    USU_ID INT,
    FOREIGN KEY (ARQT_ID) REFERENCES ARQUIVOTIPO(ARQT_ID),
    FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID)
);

CREATE TABLE AREA (
    AREA_ID INT PRIMARY KEY AUTO_INCREMENT,
    AREA_DATACADASTRO DATE NOT NULL,
    AREA_HORACADASTRO TIME NOT NULL,
    AREA_DESCRICAO VARCHAR(250),
    AREA_ATIVO TINYINT(1) DEFAULT '1'
);

CREATE TABLE AREASUB(
    AREAS_ID INT PRIMARY KEY AUTO_INCREMENT,
    AREAS_DATACADASTRO DATE NOT NULL,
    AREAS_HORACADASTRO TIME NOT NULL,
    AREAS_DESCRICAO VARCHAR(250),
    AREAS_ATIVO TINYINT(1) DEFAULT '1',
    AREA_ID INT,
    FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID)
);

CREATE TABLE USUARIOAREA (
    USUA_ID INT PRIMARY KEY AUTO_INCREMENT,
    USUA_DATACADASTRO DATE NOT NULL,
    USUA_HORACADASTRO TIME NOT NULL,
    USU_ID INT,
    AREA_ID INT,
    AREAS_ID INT,
    FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID),
    FOREIGN KEY (AREAS_ID) REFERENCES AREASUB(AREAS_ID),
    FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID)
);

CREATE TABLE CURSO(
    CUR_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CUR_DATACADASTRO DATE NOT NULL,
    CUR_HORACADASTRO TIME NOT NULL,
    CUR_DESCRICAO VARCHAR(250),
    CUR_ATIVO TINYINT(1) DEFAULT '1',
    AREA_ID INT,
    AREAS_ID INT,
    FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID),
    FOREIGN KEY (AREAS_ID) REFERENCES AREASUB(AREAS_ID)
);

CREATE TABLE MATERIA (
    MAT_ID INT PRIMARY KEY AUTO_INCREMENT,
    MAT_DATACADASTRO DATE NOT NULL,
    MAT_HORACADASTRO TIME NOT NULL,
    MAT_DESCRICAO VARCHAR(250),
    MAT_ATIVO TINYINT(1) DEFAULT '1',
    AREA_ID INT,
    AREAS_ID INT,
    FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID),
    FOREIGN KEY (AREAS_ID) REFERENCES AREASUB(AREAS_ID)
);

CREATE TABLE QUESTIONARIOTIPO (
    QUEST_ID INT PRIMARY KEY AUTO_INCREMENT,
    QUEST_DESCRICAO VARCHAR(100),
    QUEST_ATIVO TINYINT(1) DEFAULT '1'
);

CREATE TABLE QUESTIONARIO (
    QUES_ID INT PRIMARY KEY AUTO_INCREMENT,
    QUES_DATACADASTRO DATE NOT NULL,
    QUES_HORACADASTRO TIME NOT NULL,
    QUES_DESCRICAO VARCHAR(250),
    QUES_PESO INT,
    QUES_ATIVO TINYINT(1) DEFAULT '1',
    QUEST_ID INT,
    AREA_ID INT,
    AREAS_ID INT,
    FOREIGN KEY (QUEST_ID) REFERENCES QUESTIONARIOTIPO(QUEST_ID),
    FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID),
    FOREIGN KEY (AREAS_ID) REFERENCES AREASUB(AREAS_ID)
);

CREATE TABLE QUESTAOTIPO (
    QUET_ID INT PRIMARY KEY AUTO_INCREMENT,
    QUET_DESCRICAO VARCHAR(250),
    QUET_ATIVO TINYINT(1) DEFAULT '1'
);

CREATE TABLE QUESTAONIVEL(
    QUESN_ID INT PRIMARY KEY AUTO_INCREMENT,
    QUESN_DESCRICAO VARCHAR(200),
    QUESN_ATIVO TINYINT(1) DEFAULT '1'
);

CREATE TABLE QUESTAO (
    QUESTAO_ID INT PRIMARY KEY AUTO_INCREMENT,
    QUESTAO_DATACADASTRO DATE NOT NULL,
    QUESTAO_HORACADASTRO TIME NOT NULL,
    QUESTAO_CODIGO VARCHAR(50),
    QUESTAO_DESCRICAO VARCHAR(500) NOT NULL,
    QUESTAO_EXPERIENCIA INT,
    QUESTAO_ATIVO TINYINT(1) DEFAULT '1',
    QUESN_ID INT,
    QUET_ID INT,
    AREA_ID INT,
    AREAS_ID INT,
    FOREIGN KEY (QUESN_ID) REFERENCES QUESTAONIVEL(QUESN_ID),
    FOREIGN KEY (QUET_ID) REFERENCES QUESTAOTIPO(QUET_ID),
    FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID),
    FOREIGN KEY (AREAS_ID) REFERENCES AREASUB(AREAS_ID)
);

CREATE TABLE QUESTAOALTERNATIVA(
    QUESA_ID INT PRIMARY KEY AUTO_INCREMENT,
    QUESA_DESCRICAO VARCHAR(500),
    QUESA_CORRETA INT,
    QUESA_ATIVO TINYINT(1) DEFAULT '1',
    QUESTAO_ID INT,
    FOREIGN KEY (QUESTAO_ID) REFERENCES QUESTAO(QUESTAO_ID)
);

CREATE TABLE QUESTIONARIOQUESTAO(
    QUESTQ_ID INT PRIMARY KEY AUTO_INCREMENT,
    QUESTQ_DATACADASTRO DATE NOT NULL,
    QUESTQ_HORACADASTRO TIME NOT NULL,
    QUESTQ_ATIVO TINYINT(1) DEFAULT '1',
    QUES_ID INT,
    QUESTAO_ID INT,
    FOREIGN KEY (QUES_ID) REFERENCES QUESTIONARIO(QUES_ID),
    FOREIGN KEY (QUESTAO_ID) REFERENCES QUESTAO(QUESTAO_ID)
);

CREATE TABLE TESTE(
    TES_ID INT PRIMARY KEY AUTO_INCREMENT,
    TES_DATACADASTRO DATE NOT NULL,
    TES_HORACADASTRO TIME NOT NULL,
    TES_DESCRICAO VARCHAR(500) NOT NULL,
    AREA_ID INT,
    AREAS_ID INT,
    FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID),
    FOREIGN KEY (AREAS_ID) REFERENCES AREASUB(AREAS_ID)
);

CREATE TABLE TESTEQUESTAO(
    TESQ_ID INT PRIMARY KEY AUTO_INCREMENT,
    TESQ_DATACADASTRO DATE NOT NULL,
    TESQ_HORACADASTRO TIME NOT NULL,
    TESQ_DESCRICAO VARCHAR(500) NOT NULL,
    AREA_ID INT,
    AREAS_ID INT,
    FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID),
    FOREIGN KEY (AREAS_ID) REFERENCES AREASUB(AREAS_ID)
);

CREATE TABLE TESTEQUESTAOVINCULO(
    TESQV_ID INT PRIMARY KEY AUTO_INCREMENT,
    TES_ID INT,
    TESQ_ID INT,
    FOREIGN KEY (TES_ID) REFERENCES TESTE(TES_ID),
    FOREIGN KEY (TESQ_ID) REFERENCES TESTEQUESTAO(TESQ_ID)
);

CREATE TABLE TESTEQUESTAORESPONDIDA(
    TESQR_ID INT PRIMARY KEY AUTO_INCREMENT,
    TESQR_DATACADASTRO DATE NOT NULL,
    TESQR_HORACADASTRO TIME NOT NULL,
    TESQV_ID INT,
    USU_ID INT,
    TESQR_RESPOSTA INT,
    FOREIGN KEY (TESQV_ID) REFERENCES TESTEQUESTAOVINCULO(TESQV_ID),
    FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID)
);